<?php
$quotes = [
    "Carpe diem.",
    "Stay positive.",
    "Make today amazing.",
    "Focus on the good.",
    "Keep moving forward.",
    "Believe in you.",
    "You got this.",
    "Dream. Plan. Do.",
    "Stay the course.",
    "Embrace change.",
    "Shine bright.",
    "Keep it simple.",
    "Live with purpose.",
    "Rise each time.",
    "Stay curious.",
    "Trust the process.",
    "Start with hope.",
    "Never give up.",
    "Progress, not perfection.",
    "One step more.",
    "Stay humble.",
    "Find your why.",
    "Be the light.",
    "Chase the sun.",
    "Choose kindness.",
    "Keep learning.",
    "Grow through it.",
    "You are enough.",
    "Stay strong.",
    "Focus and flourish.",
    "Live with heart.",
    "Create your path.",
    "Go the distance.",
    "Smile today.",
    "Make it happen.",
    "Courage over fear.",
    "Grind and shine.",
    "Keep faith alive.",
    "Work hard, rest.",
    "Push your limits.",
    "Let it flow.",
    "Stay patient.",
    "Good vibes only.",
    "You can do it.",
    "Lead with love.",
    "Enjoy the moment.",
    "Start again.",
    "Keep showing up.",
    "Strive for more.",
    "Take the leap.",
    "Trust yourself.",
    "Stay mindful.",
    "Be unstoppable.",
    "Move with grace.",
    "Hold the vision.",
    "Endure and grow.",
    "Find your fire.",
    "Inspire others.",
    "Seek the truth.",
    "Dare to dream.",
    "Keep shining.",
    "Stay motivated.",
    "Stay the path.",
    "Rise and grind.",
    "Faith over fear.",
    "Embrace today.",
    "Love deeply.",
    "Be present now.",
    "Stay authentic.",
    "Breathe and go.",
    "Act with courage.",
    "Live in hope.",
    "Be resilient.",
    "Find your peace.",
    "Trust your gut.",
    "Win the day.",
    "Keep pushing.",
    "Do good daily.",
    "Make your mark.",
    "Focus, then act.",
    "Rise again.",
    "Seek progress.",
    "You are brave.",
    "Stay positive.",
    "Keep the faith.",
    "Live, learn, grow.",
    "Balance is key.",
    "Follow your joy.",
    "Stay grounded.",
    "Hustle smart.",
    "Let go, grow.",
    "Take the risk.",
    "Shine anyway.",
    "Find the beauty.",
    "Step by step.",
    "Stay kind.",
    "Own your story.",
    "Breathe deeply.",
    "Start small.",
    "Keep believing.",
    "Aim higher.",
    "Give your best.",
    "One day more.",
    "Be fearless.",
    "Trust the journey.",
    "Stay inspired.",
    "Make it count."
];
?>
